//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchDataShow.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurchDataShow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AGEU
        ///AMÓS
        ///APOCALIPSE
        ///ATOS
        ///CANTARES DE SALOMÃO
        ///COLOSSENSES
        ///DANIEL
        ///DEUTERONÔMIO
        ///ECLESIASTES
        ///EFÉSIOS
        ///ESDRAS
        ///ESTER
        ///ÊXODO
        ///EZEQUIEL
        ///FILEMOM
        ///FILIPENSES
        ///GÁLATAS
        ///GÊNESIS
        ///HABACUQUE
        ///HEBREUS
        ///I CORINTIOS
        ///I CRÔNICAS
        ///I JOÃO
        ///I PEDRO
        ///I REIS
        ///I SAMUEL
        ///I TESSALONICENSES
        ///I TIMÓTEO
        ///II CORINTIOS
        ///II CRÔNICAS
        ///II JOÃO
        ///II PEDRO
        ///II REIS
        ///II SAMUEL
        ///II TESSALONICENSES
        ///II TIMÓTEO
        ///III JOÃO
        ///ISAÍAS
        ///JEREMIAS
        ///JÓ
        ///JOÃO
        ///JOEL
        ///JONAS
        ///JOSUÉ
        ///JUDAS
        ///JUÍZES
        ///LAMENTAÇÕES DE JEREMIAS
        ///LEVÍTICO
        ///LUCAS
        ///MALAQUIAS        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Livros {
            get {
                return ResourceManager.GetString("Livros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;MATEUS [1]
        ///1 Livro da genealogia de Jesus Cristo, filho de Davi, filho de Abraão.
        ///2 A Abraão nasceu Isaque; a Isaque nasceu Jacó; a Jacó nasceram Judá e seus irmãos;
        ///3 a Judá nasceram, de Tamar, Farés e Zará; a Farés nasceu Esrom; a Esrom nasceu Arão;
        ///4 a Arão nasceu Aminadabe; a Aminadabe nasceu Nasom; a Nasom nasceu Salmom;
        ///5 a Salmom nasceu, de Raabe, Booz; a Booz nasceu, de Rute, Obede; a Obede nasceu Jessé;
        ///6 e a Jessé nasceu o rei Davi. A Davi nasceu Salomão da que fora mulher de Urias;
        ///7 a Sa [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Novo_ib {
            get {
                return ResourceManager.GetString("Novo_ib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;MATEUS [1]
        ///1 Livro da genealogia de Jesus Cristo, filho de Davi, filho de Abraão.
        ///2 A Abraão nasceu Isaque; a Isaque nasceu Jacó; a Jacó nasceram Judá e seus irmãos;
        ///3 a Judá nasceram, de Tamar, Farés e Zará; a Farés nasceu Esrom; a Esrom nasceu Arão;
        ///4 a Arão nasceu Aminadabe; a Aminadabe nasceu Nasom; a Nasom nasceu Salmom;
        ///5 a Salmom nasceu, de Raabe, Booz; a Booz nasceu, de Rute, Obede; a Obede nasceu Jessé;
        ///6 e a Jessé nasceu o rei Davi. A Davi nasceu Salomão da que fora mulher de Urias;
        ///7 a Sa [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Novo_JFA {
            get {
                return ResourceManager.GetString("Novo_JFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;MATEUS [1]
        ///1. Livro da genealogia de Jesus Cristo, filho de Davi, filho de Abraão.
        ///2. Abraão gerou a Isaque; Isaque, a Jacó; Jacó, a Judá e a seus irmãos;
        ///3. Judá gerou de Tamar a Perez e a Zera; Perez gerou a Esrom; Esrom, a Arão;
        ///4. Arão gerou a Aminadabe; Aminadabe, a Naassom; Naassom, a Salmom;
        ///5. Salmom gerou de Raabe a Boaz; este, de Rute, gerou a Obede; e Obede, a Jessé;
        ///6. Jessé gerou ao rei Davi; e o rei Davi, a Salomão, da que fora mulher de Urias;
        ///7. Salomão gerou a Roboão; Roboão, a Abia [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Novo_RA {
            get {
                return ResourceManager.GetString("Novo_RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;MATEUS [1]
        ///1. Livro da geração de Jesus Cristo, Filho de Davi, Filho de Abraão.
        ///2. Abraão gerou a Isaque, e Isaque gerou a Jacó, e Jacó gerou a Judá e a seus irmãos,
        ///3. e Judá gerou de Tamar a Perez e a Zerá, e Perez gerou a Esrom, e Esrom gerou a Arão.
        ///4. Arão gerou a Aminadabe, e Aminadabe gerou a Naassom, e Naassom gerou a Salmom,
        ///5. e Salmom gerou de Raabe a Boaz, e Boaz gerou de Rute a Obede, e Obede gerou a Jessé.
        ///6. Jessé gerou ao rei Davi, e o rei Davi gerou a Salomão da que foi mulher de Uri [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Novo_RC {
            get {
                return ResourceManager.GetString("Novo_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;GÊNESIS [1]
        ///1 No princípio criou Deus os céus e a terra.
        ///2 A terra era sem forma e vazia; e havia trevas sobre a face do abismo, mas o Espírito de Deus pairava sobre a face das águas.
        ///3 Disse Deus: haja luz. E houve luz.
        ///4 Viu Deus que a luz era boa; e fez separação entre a luz e as trevas.
        ///5 E Deus chamou à luz dia, e às trevas noite. E foi a tarde e a manhã, o dia primeiro.
        ///6 E disse Deus: haja um firmamento no meio das águas, e haja separação entre águas e águas.
        ///7 Fez, pois, Deus o firmamento, e [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Velho_ib {
            get {
                return ResourceManager.GetString("Velho_ib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;GÊNESIS [1]
        ///1 No princípio criou Deus os céus e a terra.
        ///2 A terra era sem forma e vazia; e havia trevas sobre a face do abismo, mas o Espírito de Deus pairava sobre a face das águas.
        ///3 Disse Deus: haja luz. E houve luz.
        ///4 Viu Deus que a luz era boa; e fez separação entre a luz e as trevas.
        ///5 E Deus chamou à luz dia, e às trevas noite. E foi a tarde e a manhã, o dia primeiro.
        ///6 E disse Deus: haja um firmamento no meio das águas, e haja separação entre águas e águas.
        ///7 Fez, pois, Deus o firmamento, e [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Velho_JFA {
            get {
                return ResourceManager.GetString("Velho_JFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;GÊNESIS [1]
        ///1. No princípio, criou Deus os céus e a terra.
        ///2. A terra, porém, estava sem forma e vazia; havia trevas sobre a face do abismo, e o Espírito de Deus pairava por sobre as águas.
        ///3. Disse Deus: Haja luz; e houve luz.
        ///4. E viu Deus que a luz era boa; e fez separação entre a luz e as trevas.
        ///5. Chamou Deus à luz Dia e às trevas, Noite. Houve tarde e manhã, o primeiro dia.
        ///6. E disse Deus: Haja firmamento no meio das águas e separação entre águas e águas.
        ///7. Fez, pois, Deus o firmamento e se [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Velho_RA {
            get {
                return ResourceManager.GetString("Velho_RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;GÊNESIS [1]
        ///1. No princípio, criou Deus os céus e a terra.
        ///2. E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.
        ///3. E disse Deus: Haja luz. E houve luz.
        ///4. E viu Deus que era boa a luz; e fez Deus separação entre a luz e as trevas.
        ///5. E Deus chamou à luz Dia; e às trevas chamou Noite. E foi a tarde e a manhã: o dia primeiro.
        ///6. E disse Deus: Haja uma expansão no meio das águas, e haja separação entre águas e águas.
        ///7. E fez D [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Velho_RC {
            get {
                return ResourceManager.GetString("Velho_RC", resourceCulture);
            }
        }
    }
}
